# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ModelResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, expression=None, parameters=None):  # noqa: E501
        """ModelResponse - a model defined in OpenAPI

        :param expression: The expression of this ModelResponse.  # noqa: E501
        :type expression: str
        :param parameters: The parameters of this ModelResponse.  # noqa: E501
        :type parameters: List[str]
        """
        self.openapi_types = {
            'expression': str,
            'parameters': List[str]
        }

        self.attribute_map = {
            'expression': 'expression',
            'parameters': 'parameters'
        }

        self._expression = expression
        self._parameters = parameters

    @classmethod
    def from_dict(cls, dikt) -> 'ModelResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The model_response of this ModelResponse.  # noqa: E501
        :rtype: ModelResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def expression(self):
        """Gets the expression of this ModelResponse.


        :return: The expression of this ModelResponse.
        :rtype: str
        """
        return self._expression

    @expression.setter
    def expression(self, expression):
        """Sets the expression of this ModelResponse.


        :param expression: The expression of this ModelResponse.
        :type expression: str
        """
        if expression is None:
            raise ValueError("Invalid value for `expression`, must not be `None`")  # noqa: E501

        self._expression = expression

    @property
    def parameters(self):
        """Gets the parameters of this ModelResponse.


        :return: The parameters of this ModelResponse.
        :rtype: List[str]
        """
        return self._parameters

    @parameters.setter
    def parameters(self, parameters):
        """Sets the parameters of this ModelResponse.


        :param parameters: The parameters of this ModelResponse.
        :type parameters: List[str]
        """
        if parameters is None:
            raise ValueError("Invalid value for `parameters`, must not be `None`")  # noqa: E501

        self._parameters = parameters
