# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ModelRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, expression=None):  # noqa: E501
        """ModelRequest - a model defined in OpenAPI

        :param expression: The expression of this ModelRequest.  # noqa: E501
        :type expression: str
        """
        self.openapi_types = {
            'expression': str
        }

        self.attribute_map = {
            'expression': 'expression'
        }

        self._expression = expression

    @classmethod
    def from_dict(cls, dikt) -> 'ModelRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The model_request of this ModelRequest.  # noqa: E501
        :rtype: ModelRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def expression(self):
        """Gets the expression of this ModelRequest.


        :return: The expression of this ModelRequest.
        :rtype: str
        """
        return self._expression

    @expression.setter
    def expression(self, expression):
        """Sets the expression of this ModelRequest.


        :param expression: The expression of this ModelRequest.
        :type expression: str
        """
        if expression is None:
            raise ValueError("Invalid value for `expression`, must not be `None`")  # noqa: E501

        self._expression = expression
